### ISSUE TITLE
mkdocs 1.2 not compatible with some knative-specific extensions

### ISSUE THREAD

**Issue by psschwei** [knative/docs#3765]
Was following the instructions to install Mkdocs and encountered the following error:

```
$ pip list installed | grep mkdocs
mkdocs                      1.2.1
mkdocs-awesome-pages-plugin 2.5.0
mkdocs-exclude              1.0.2
mkdocs-macros-plugin        0.5.5
mkdocs-material             7.1.7
mkdocs-material-extensions  1.0.1
mkdocs-redirects            1.0.3
WARNING: You are using pip version 21.0.1; however, version 21.1.2 is available.
You should consider upgrading via the '/home/paulschw/knative/docs/venv/bin/python3 -m pip install --upgrade pip' command.                                                                                        

$ mkdocs serve
INFO     -  Building documentation...
<snip>
INFO     -  Documentation built in 9.29 seconds
Traceback (most recent call last):
  File "/home/paulschw/knative/docs/venv/bin/mkdocs", line 8, in <module>
    sys.exit(cli())
  File "/home/paulschw/knative/docs/venv/lib64/python3.9/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/home/paulschw/knative/docs/venv/lib64/python3.9/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/home/paulschw/knative/docs/venv/lib64/python3.9/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/paulschw/knative/docs/venv/lib64/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/paulschw/knative/docs/venv/lib64/python3.9/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/home/paulschw/knative/docs/venv/lib64/python3.9/site-packages/mkdocs/__main__.py", line 173, in serve_command
    serve.serve(dev_addr=dev_addr, livereload=livereload, **kwargs)
  File "/home/paulschw/knative/docs/venv/lib64/python3.9/site-packages/mkdocs/commands/serve.py", line 78, in serve
    server = config['plugins'].run_event('serve', server, config=config, builder=builder)
  File "/home/paulschw/knative/docs/venv/lib64/python3.9/site-packages/mkdocs/plugins.py", line 94, in run_event
    result = method(item, **kwargs)
  File "/home/paulschw/knative/docs/venv/lib64/python3.9/site-packages/mkdocs_macros/plugin.py", line 588, in on_serve
    builder = list(server.watcher._tasks.values())[0]["func"]
AttributeError: 'LiveReloadServer' object has no attribute 'watcher'
```

Based on [this Mkdocs issue](https://github.com/mkdocs/mkdocs/issues/2446), it looks like the most current version of Mkdocs (1.2) is not currently compatible with some of the plugins we're using. 

A simple fix is to pin the version of Mkdocs, i.e. `pip install mkdocs==1.1.2`

**Comment by julz** [comment]
I think the linked issue is a _slight_ red herring: that's talking about a plugin (monorepo) that we don't use.

Looks like the actual problem is with mkdocs-macros-plugin (see https://github.com/fralau/mkdocs_macros_plugin/issues/86). The good news is it only affects `mkdocs serve` locally (otherwise the netlify builds would have stopped working since [they're using mkdocs 1.2 already](https://app.netlify.com/sites/dev-knative/deploys/60c0fce135adf50008d67da6?utm_source=github&utm_campaign=bot_dl#L70)!).

Folks should probably avoid upgrading mkdocs locally for a day or two until https://github.com/fralau/mkdocs_macros_plugin/issues/86 is fixed (and run the line above if they need to downgrade), but since the builds are working fine with 1.2 I dont _think_ we need to do anything in the repo.

**Comment by snneji** [comment]
@psschwei is this still an issue?

**Comment by psschwei** [comment]
> @psschwei is this still an issue?

No, it's working now.
